version: '2.1'

services:
  php:
    build:
      context: ./application
      args:
        TIMEZONE: ${TIMEZONE}
    volumes:
      - ./${SERVICE_ROOT_PATH}:/srv/service
    environment:
      APP_ENV: "dev"
      APP_DEBUG: "true"
      PHP_IDE_CONFIG: "serverName=docker.dev"
    depends_on:
      - postgres

  nginx:
    build: ./docker/nginx
    ports:
      - "9000:80"
    volumes:
      - ${SERVICE_ROOT_PATH}/public:/srv/service/public:ro
    depends_on:
      - php
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./.data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4:4.6
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5433:80"
    depends_on:
    - postgres

